In [6]:
import numpy

#Ej1: Para 5(cinco) paginas: {A,B,C,D,E} sean los siguientes links
#(A,B)
#(A,C)
#(A,D)
#(B,C)
#(B,D)
#(C,B)
#(C,E)
#(D,A)
#(D,B)
#(E,C)
#Calcular el Simrank para la pagina A con b=0.7 y luego identificar la opcion correcta entre las siguientes: 
#a)El ranking de semejanza con A es B,C,D,E 
#b)La pagina menos similar a "A" es C 
#c)El ranking de semejanza con A es D,B,C,E 
#d)La pagina mas similar a "A" es D 

def PageRank(M, vector, b, tVec, nIter):
    prVector = vector
    teletransportation = 1 - b
    for i in xrange(0,nIter):
        prVector = b*M*prVector + teletransportation*tVec
    return prVector

M = numpy.matrix([[0,0,0,0.5,0],[0.33,0,0.5,0.5,0],[0.33,0.5,0,0,1],[0.33,0.5,0,0,0],[0,0,0.5,0,0]])
tVec = numpy.matrix([[1],[0],[0],[0],[0]])
prVector = numpy.matrix([[0.2],[0.2],[0.2],[0.2],[0.2]])

print PageRank(M,prVector,0.7,tVec, 100)

#Rta: SimRank(A): B,C,D,E

[[ 0.35402443]
 [ 0.2073596 ]
 [ 0.20444437]
 [ 0.1543555 ]
 [ 0.07155553]]


In [10]:
# Ej3: Para 5(cinco) paginas: {A,B,C,D,E} sean los siguientes links
#(A,B)
#(A,C)
#(A,D)
#(B,C)
#(B,D)
#(C,B)
#(C,E)
#(D,A)
#(D,B)
#Usando b=0.8 calcular el PR a partir del vector [1,1,1,1,1] y luego identificar la opcion correcta entre las siguientes:   
#a)A tiende a 0.5 aproximadamente 
#b)La pagina con mayor PR es B 
#c)La pagina con mayor PR es D 
#d)En la primera iteracion C=0.75 


M = numpy.matrix([[0,0,0,0.5,0],[0.33,0,0.5,0.5,0],[0.33,0.5,0,0,0],[0.33,0.5,0,0,0],[0,0,0.5,0,0]])
deadEndFix = numpy.matrix([[0,0,0,0,0.2],[0,0,0,0,0.2],[0,0,0,0,0.2],[0,0,0,0,0.2],[0,0,0,0,0.2] ])
tVec = numpy.matrix([[0.2],[0.2],[0.2],[0.2],[0.2]])
prVector = numpy.matrix([[1],[1],[1],[1],[1]])

print "PR after 1 iteration:\n" + str( PageRank(M + deadEndFix,prVector,0.8,tVec, 1) ) + "\n"
print "PR after 100 iterations:\n" + str(PageRank(M + deadEndFix,prVector,0.8,tVec, 100) ) + "\n"

#Rta: b)La pagina con mayor PR es B 

PR after 1 iteration:
[[ 0.6  ]
 [ 1.264]
 [ 0.864]
 [ 0.864]
 [ 0.6  ]]

PR after 100 iterations:
[[ 0.14860978]
 [ 0.27267498]
 [ 0.21208054]
 [ 0.21208054]
 [ 0.14860978]]



In [11]:
#Sea el siguiente grafo: 
#(A,B)
#(B,C)
#(A,C)
#(C,A)
#Calcular el pagerank con b=0.85. Escribir la ecuacion de pagerank para cada uno de los tres nodos: a,b,c y luego identificar la ecuacion correcta de la siguiente lista: 
#a) .85b = .575a + .15c 
#b) a = .9c + .05b 
#c) .95c = .9b + .475a 
#d) b = .475a + .05c 

M = numpy.matrix([[0,0,1],[0.5,0,0],[0.5,1,0]])
tVec = numpy.matrix([[0.33],[0.33],[0.33]])
prVector = numpy.matrix([[0.33],[0.33],[0.33]])

print "PR after 100 iterations:\n" + str(PageRank(M, prVector,0.85,tVec, 100) ) + "\n"

#Rta: c) .95c = .9b + .475a 

PR after 100 iterations:
[[ 0.38391181]
 [ 0.21266252]
 [ 0.39342566]]



In [15]:
#Calcular el PageRank tematico para el siguiente grafo. 
#(1,3)
#(1,2)
#(2,1)
#(3,4)
#(4,3)
#Asumir que los nodos que representan el tema de interes son el 1 y el 2 y que el peso del nodo 1 es el doble del tema 2. Usar b=0.7. Y luego identificar la opcion correcta entre las siguientes: 
#a) TSPR(3) = .9097 
#b) TSPR(1) = .2455 
#c) TSPR(2) = .8998 
#d) TSPR(4) = .1718 

M = numpy.matrix([[0,1,0,0],[0.5,0,0,0],[0.5,0,0,1],[0,0,1,0]])
tVec = numpy.matrix([ [0.6667],[0.3333],[0],[0] ])
prVector = numpy.matrix([ [0.25],[0.25],[0.25],[0.25] ])

print "PR after 100 iterations:\n" + str( PageRank(M, prVector,0.7,tVec, 100) ) + "\n"

#Rta: d) TSPR(4) = .1718 


PR after 100 iterations:
[[ 0.35761987]
 [ 0.22515695]
 [ 0.2454254 ]
 [ 0.17179778]]



In [16]:
#Sea el siguiente grafo: 
#(A,B)
#(B,C)
#(A,C)
#(C,A)

#Sin usar teletransportacion calcular el PageRank de a,b,c partiendo de a=1,b=1,c=1 realizando 5 iteraciones. 
#Calcular tambien el valor de convergencia del PageRank. Luego identificar la opcion correcta: 
#a) Luego de la iteracion 4 b=3/5 
#b) Luego de la iteracion 4 c=4/3 
#c) Luego de la iteracion 4 a=5/4 
#d) Luego de la iteracion 5 c=7/4 

M = numpy.matrix([[0,0,1],[0.5,0,0],[0.5,1,0]])
tVec = numpy.matrix([[0],[0],[0]])
prVector = numpy.matrix([[1],[1],[1]])

print "PR after 4 iterations:\n" + str(PageRank(M, prVector,1,tVec, 4) ) + "\n"
print "PR after 5 iterations:\n" + str(PageRank(M, prVector,1,tVec, 5) ) + "\n"
print "PR after 100 iterations:\n" + str(PageRank(M, prVector,1,tVec, 100) ) + "\n"

#Rta: c) Luego de la iteracion 4 a=5/4 

PR after 4 iterations:
[[ 1.25]
 [ 0.5 ]
 [ 1.25]]

PR after 5 iterations:
[[ 1.25 ]
 [ 0.625]
 [ 1.125]]

PR after 100 iterations:
[[ 1.2]
 [ 0.6]
 [ 1.2]]

